### ISSUE TITLE
Update for Documentation

### ISSUE THREAD

**Issue by awanczowski** [marklogic-community/grove#35]
It looks like the documentation on https://marklogic-community.github.io/grove/guides/react/recipes/search-results has an old import clause. 

old: `import { CardResult, SearchView, SearchSnippet} from 'grove-core-react-components';`

new: `import { CardResult, SearchView, SearchSnippet} from '@marklogic-community/grove-core-react-components';`

**Comment by mariannemyers** [comment]
This is now OBE with the refactor of grove-react-ui that added the contents of `@marklogic-community/grove-core-react-components` to the UI directly.
