### ISSUE TITLE
What is/Why Marklogic Grove?

### ISSUE THREAD

**Issue by dsgrgiftson** [marklogic-community/grove#44]
Just had a glance at the Grove documentation. It simply mentions about a middle-tier and a front-end providing some operations which were supposedly to be workaround on some areas. Correct me if I'm wrong.

I however did not understand the purpose of Grove and what benefit it would provide me or the project which is backed by Marklogic?

I don't have any knowledge about Marklogic. All I know is that it's a NoSql DB and I currently use some REST API endpoints exposed by it to do some basic search operations.

Before going through the documentation without understanding the context, it would be great if someone helps me out.
Would be helpful if explained with a use-case on what is this Grove about and why would I need it.

It would be great if these details were included in the documentation.

**Comment by daveegrant** [comment]
Hopefully some of the following links help address your questions.  The bottom line is that Grove provides a starting point for a search-and-discovery application that interfaces with data in MarkLogic.  It does have the ability to add documents to MarkLogic but only in a one-document-at-a-time fashion.

https://www.marklogic.com/blog/building-ui-applications-using-grove/
https://developer.marklogic.com/code/grove/

**Comment by dsgrgiftson** [comment]
> https://www.marklogic.com/blog/building-ui-applications-using-grove/

Thank you for the comment.

The first link mentions about Grove as a a solution to these common questions "how do I connect to it? How do I get data into and out of it?"

I read something about Marklogic DataHub which provides functionality such as loading, curating and processing the data.

Is Grove something similar to a custom built DataHub that provides these functionality with more customization?

**Comment by daveegrant** [comment]
The MarkLogic DataHub is a framework that runs on top of MarkLogic Server.  It provides some commonly used concepts for modeling data (entities), ingesting data for those entities, then curating that data into the defined entity model.  The DataHub does have a UI component (Hub Central) for creating the entity models, some dev-type ingestion tools (not meant for production), and tools for the curation process.  The UI can also be used to view data as it is going through ingestion/curation and viewing the final version of the data.

Grove is a three-tier application stack where MarkLogic is the DB.  Grove can connect to an application deployed to MarkLogic Server.  A Grove application can also be configured to view data loaded via MarkLogic DataHub.  The Grove application uses MarkLogic's REST API to interface with with MarkLogic Server.

Grove is typically used as a starting point when a custom UI application is needed to access data in MarkLogic Server.  It is an extensible stack where new ReactJS/VueJS components can be added to enhance the application (e.g. - add maps, graphs, charts, custom visualizations, etc).

The Hub Central application is not extensible and is intended as more of a development tool to setup a MarkLogic DataHub and execute curation tasks.

**Comment by dsgrgiftson** [comment]
> 
> 
> The MarkLogic DataHub is a framework that runs on top of MarkLogic Server. It provides some commonly used concepts for modeling data (entities), ingesting data for those entities, then curating that data into the defined entity model. The DataHub does have a UI component (Hub Central) for creating the entity models, some dev-type ingestion tools (not meant for production), and tools for the curation process. The UI can also be used to view data as it is going through ingestion/curation and viewing the final version of the data.
> 
> Grove is a three-tier application stack where MarkLogic is the DB. Grove can connect to an application deployed to MarkLogic Server. A Grove application can also be configured to view data loaded via MarkLogic DataHub. The Grove application uses MarkLogic's REST API to interface with with MarkLogic Server.
> 
> Grove is typically used as a starting point when a custom UI application is needed to access data in MarkLogic Server. It is an extensible stack where new ReactJS/VueJS components can be added to enhance the application (e.g. - add maps, graphs, charts, custom visualizations, etc).
> 
> The Hub Central application is not extensible and is intended as more of a development tool to setup a MarkLogic DataHub and execute curation tasks.

This explanation makes more sense to me than jumping into the actual documentation. Thank you for clarifying!
