### ISSUE TITLE
Clarify in readme that the code is available via npm

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/grove#5]
Clarify where the code is, that it is FOSS, how to see it.

**Comment by patrickmcelwee** [comment]
and make the link to ~~https://github.com/marklogic-community/grove~~ https://marklogic-community.github.io/grove/ prominent in the README

**Comment by grtjn** [comment]
Or maybe the link to github.io for grove?

**Comment by patrickmcelwee** [comment]
whoops! ... that's what I meant: https://marklogic-community.github.io/grove/

**Comment by grtjn** [comment]
See also #11

**Comment by mariannemyers** [comment]
Fixed with https://github.com/marklogic-community/grove-react-template/pull/10/commits/d0e41227204e984358f253dfacee510914f12b2d
